version: "3.1"
services:
  nginx:
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    volumes:
      - "./nginx/logs:/var/log/nginx"
    ports:
        - "80:80"
        - "443:443"
        - "88:88"

  app:
    build:
      context: "./src"
      dockerfile: Dockerfile
    volumes:
      - "./app/logs:/app/logs"
