version: "3.1"
services:
  nginx:
    image:  nginx
    volumes:
      - "./logs/nginx:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nginx-ssl.webredirect.org:/etc/nginx/sites-available/nginx-ssl.webredirect.org"
      - "./nginx/cert/fullchain.pem:/fullchain.pem"
      - "./nginx/cert/privkey.pem:/privkey.pem"
    ports:
        - "80:80"
        - "443:443"
        - "88:88"

  web:
    build:
      context: "./"
      dockerfile: MyWeb.Dockerfile
    volumes:
      - "./logs/web:/app/logs"

  web2:
    build:
      context: "./"
      dockerfile: MyWeb2.Dockerfile
    volumes:
      - "./logs/web2:/app/logs"

